[[edge_functions]]
	path = "/stories"
	function = "stories"

[[edge_functions]]
	path = "/render-with-api"
	function = "render"

[[edge_functions]]
	path = "/"
	function = "main"

[build]
  publish = "public/"

  # Default build command.
  command = "echo 'default context'"
